---
title: "Critical Access Hospitals"
author: "Andres de Loera"
date: "6/10/2019"
output: html_document
---

```{r setup, include=FALSE, cache = TRUE}
knitr::opts_chunk$set(echo = TRUE)

#I begin by loading in the libraries I will use.

library(readxl)
library(janitor)
library(gt)
library(tidyverse)
library(ggthemes)

#Now I download the data on critical access hospitals 
#I downloaded and moved the excel files into my repository by hand, so here I just read them into an r object, call clean names for ease of use, add a year variable, and use select to get a consistent name, selection and ordering of variables. 

cahs_2019 <- read_excel("CAH Data/CAH_List_04_18_19.xlsx",
                        skip = 1) %>%
  clean_names() %>%
  mutate(year = 2019) %>%
  select(name, city, state = stcd, zip = zip, cert_date = cert_effective_date, beds = number_beds, year)

cahs_2018 <- read_excel("CAH Data/CAH_List_10_19_18.xlsx", 
                        skip = 1) %>%
  clean_names() %>%
  mutate(year = 2018) %>%
  select(name, city, state = stcd, zip = zip, cert_date = cert_effective_date, beds = number_beds, year)

cahs_2017 <- read_excel("CAH Data/2017-Jul-CAH-List.xlsx",
                        skip = 1) %>%
  clean_names() %>%
  mutate(year = 2017) %>%
  select(name, city, state = stcd, zip = zip, cert_date = cert_effective_date, beds = number_beds, year)

cahs_2016 <- read_excel("CAH Data/2016-Oct-CAH-List.xlsx", 
                        col_types = c("text", "text", "text", 
                                      "text", "text", "date", "numeric", 
                                      "numeric", "numeric", "numeric"), 
                        skip = 1) %>%
  clean_names() %>%
  mutate(year = 2016) %>%
  select(name, city, state = stcd, zip = zip, cert_date = cert_effective_date, beds = number_beds, year)

cahs_2015 <- read_excel("CAH Data/2015-Oct-CAH-List.xlsx",
                       skip = 1) %>%
  clean_names() %>%
  mutate(year = 2015) %>%
  select(name, city, state = stcd, zip = zip, cert_date = cert_effective_date, beds = number_beds, year)

cahs_2014 <- read_excel("CAH Data/2014-Jun-CAH-List.xlsx") %>%
  clean_names() %>%
  mutate(year = 2014) %>%
  select(name = cahname, city = cahcity, state = cahstate, zip = cahzip, cert_date = cah_eff, beds, year)


cahs_2013 <- read_excel("CAH Data/2013-Jun-CAH-List.xlsx", 
                        skip = 1) %>%
  clean_names() %>%
  mutate(year = 2013) %>%
  select(name = cahname, city = cahcity, state = cahstate, zip = cahzip, cert_date = cah_eff, beds, year)

cahs_2012 <- read_excel("CAH Data/2012-Sep-CAH-List.xlsx", 
                        skip = 1) %>%
  clean_names() %>%
  mutate(year = 2012) %>%
  select(name = cahname, city = cahcity, state = cahstate, zip = cahzip, cert_date = cah_eff, beds, year)

cahs_2011 <- read_excel("CAH Data/2011-Mar-CAH-List.xlsx",
                        skip = 1) %>%
  clean_names() %>%
  mutate(year = 2011) %>%
  select(name = cahname, city = cahcity, state = cahstate, zip = cahzip, cert_date = cah_eff, beds, year)

  
cahs_2010 <- read_excel("CAH Data/2010-Sep-CAH-List.xlsx",
                        skip = 1) %>%
  clean_names() %>%
  mutate(year = 2010) %>%
  select(name = cahname, city = cahcity, state = cahstate, zip = cahzip, cert_date = cah_eff, beds, year)
  

cahs_2009 <- read_excel("CAH Data/2009-Jul-CAH-List.xlsx",
                        skip = 1) %>%
  clean_names() %>%
  mutate(year = 2009) %>%
  select(name = cahname, city = cahcity, state = cahstate, zip = cahzip, cert_date = cah_eff, beds, year)

cahs_2008 <- read_excel("CAH Data/2008-Sep-CAH-List.xlsx",
                        skip = 1) %>%
  clean_names() %>%
  mutate(year = 2008) %>%
  select(name = cahname, city = cahcity, state = cahstate, zip = cahzip, cert_date = cah_eff, beds, year)

cahs_2007 <- read_excel("CAH Data/2007-Aug-CAH-List.xlsx",
                        skip = 1) %>%
  clean_names() %>%
  mutate(year = 2007) %>%
  select(name = cahname, city = cahcity, state = cahstate, zip = cahzip, cert_date = cah_eff, beds = number_beds, year)

#Then I bind the consistent dataset together.

cahs_all <- rbind(cahs_2007, 
                  cahs_2008, 
                  cahs_2009, 
                  cahs_2010, 
                  cahs_2011, 
                  cahs_2012, 
                  cahs_2013, 
                  cahs_2014, 
                  cahs_2015, 
                  cahs_2016, 
                  cahs_2017, 
                  cahs_2018, 
                  cahs_2019)

```


```{r beds, echo = FALSE, cache = TRUE, warning = FALSE}

#Here I create visualizations of the distribution of critical access hospitals by hospital beds.

#First for 2019

cahs_2019 %>%
  ggplot(aes(x = beds, fill = "red")) +
  geom_bar() +
  labs(title = "Critical Access Hospitals by Number of Beds",
       caption = "Data from Flex Monitoring Team, 2019", 
       x = "Number of Beds",
       y = "Number of CAHs") +
  scale_fill_calc(guide = FALSE) + 
  theme_calc()

#and then for the prior years going back to 2007.

cahs_all %>%
  filter(year != 2019) %>%
  ggplot(aes(x = beds, fill = "blue")) +
  geom_bar() +
  labs(title = "Critical Access Hospitals by Number of Beds",
       caption = "Data from Flex Monitoring Team, 2007-2018", 
       x = "Number of Beds",
       y = "Number of CAHs") +
  facet_wrap(~year) +  
  scale_fill_calc(guide = FALSE) + 
  theme_calc()

#I also try a scatterplot (with jitter) representation for all the years.

cahs_all %>%
  ggplot(aes(x = year, y = beds, color = "2")) +
  geom_jitter(alpha = 0.1) +
  labs(x = "Year",
       y = "Beds in Critical Access Hospitals",
       caption = "Data from Flex Monitoring Team, 2007-2019") +
  scale_x_continuous(breaks = c(2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019),
                     labels = c("2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019")) +
  scale_y_continuous(breaks = c(0, 5, 10, 15, 20, 25), 
                     labels = c("0", "5", "10", "15", "20", "25")) +
  scale_color_calc(guide = FALSE) + 
  theme_calc()
  
```


```{r TX, echo = FALSE, cache = TRUE}

#Here I want to visualize the distribution of texas hospitals by hospital beds with attention to critical access designation. 
#First I read in the data and select texas critical access hospitals.

tx_hospitals_2019 <- read_excel("CAH Data/TX GenSpecHosDirectory.xlsx") %>%
  clean_names() %>%
  mutate(name = tolower(name),
         zip = as.character(zip)) 

tx_cahs_2019 <- cahs_2019 %>%
  filter(state == "TX") %>%
  mutate(critical_access = 1,
         name = tolower(name))

##Then I match the datasets using my hand constructed matching spreadsheet. 

tx_match_2019 <- read_excel("matching.xlsx") %>%
  full_join(tx_hospitals_2019, by = c("name_hospital" = "name", "city_hospital" = "city")) %>%
  full_join(tx_cahs_2019, by = c("name_cah" = "name", "city_cah" = "city")) %>%
  mutate(critical_access = replace_na(critical_access, 0),
         critical_access = as.factor(critical_access))

#Finally I made a bar chart. 

tx_match_2019 %>%
  filter(med_surg_beds < 51) %>%
  ggplot(aes(x = med_surg_beds, fill = critical_access)) +
  geom_bar() +
  labs(title = "Medical/Surgical Beds in Texas Hospitals",
       subtitle = "(Hospital with 50 or fewer beds in 2019)",
       x = "Number of Beds",
       y = "Count of Hospitals",
       caption = "Data from the Texas Department of Health and Human Services",
       fill = element_blank()) +
  scale_x_continuous(breaks = c(0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50),
                     labels = c("0", "5", "10", "15", "20", "25", "30", "35", "40", "45", "50")) +
  scale_y_continuous(breaks = c(0, 5, 10, 15, 20, 25, 30),
                     labels = c("0", "5", "10", "15", "20", "25", "30")) +
  scale_fill_calc(breaks = c(1,0),
                  labels = c("Critical Access", "Not CAH")) +
  theme_calc()


```
